config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  scope "(:locale)", locale: /en|vi/ do
    get 'static_pages/home'
    get  "/help",    to: "static_pages#help", as: "helf"
    get  "/about",   to: "static_pages#about"
    get  "/contact", to: "static_pages#contact"
    get  "/signup",  to: "users#new"
    post "/signup",  to: "users#create"
    get    "/login",   to: "sessions#new"
    post   "/login",   to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"
    get 'password_resets/new'
    get 'password_resets/edit'
    resources :users
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
  <ul>
     <li> <%= link_to "English", locale:"en" %></li>
     <li> <%= link_to "Vietnamese", locale:"vi" %></li>
  </ul>
  <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"),   root_path %></li>
        <li><%= link_to t("static_pages.help.title"),   helf_path
         %></li>
         <% if logged_in? %>
          <li><%= link_to t("users.user"), users_path %></li>
          <li class="dropdown">
            <a class=dropdown-toggle><%= t "users.account"%></a>
            <ul class="dropdown-menu">
              <li><%= link_to t("users.profile"), current_user %></li>
              <li><%= link_to t("users.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("users.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("users.login"), login_path %></li>
          <li><%= link_to t("users.signup_title"), signup_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "static_pages.sample" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>